var myString;
var myNum;
var myBool;
// let myStringArray: string[];
// let myNumArray: number[];
// let myBoolArray: boolean[];
var anyThing;
var myStringArray;
var myBoolArray;
var strNumTuple;
var myVoid = null;
myNum = 1;
myString = 'hello'.slice(1, 2);
myStringArray = ['you are so cool', 'HAHAHAHA'];
myBool = true;
myBoolArray = [false, true, true];
strNumTuple = ['heelo', 88];
anyThing = ['anything', 12, [234, '234']];
console.log(anyThing);
